[package]
name = "rust_os"
version = "0.1.1"
authors = ["Philipp Oppermann <dev@phil-opp.com>, Josh Charles <josh.charles@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"
